version: "0.1"

# colors
colors:
  black:
    base: true
    swatches:
      - Obsidian
      - Onyx
  blue:
    base: true
    swatches:
      - Cornflower
      - Electric # will generate a [light] error (will not be used (logged) but rest of config can load.)
  custom:
    name: "brand"
    swatch:
      primary: "#FF5733"
      secondary: "#33FF57"
      tertiary: "#5733FF"
      alerts:
        success: "#28a745"
        warning: "#ffc107"
        information: "#17a2b8"
        error: "#dc3545"
    definition: "something.yml"

typography:
  fonts:
    source: adobe
    url: "https://fonts.adobe.com/{typekit-url}"
    primary:
      family: "Korolev"
      weights: [400, 600, 700]
    secondary:
      family: "Korolev"
      weights: [400, 600, 700]
    tertiary:
      family: "Google Sans"
      weights: [400, 600, 700]
      source: google
      url: "https://fonts.google.com/{google-font-url}"



# Experimental
mode:
  layout: juice
  tailwind:
    use: false
    config:

  bootstrap:
    use: false
    config:
