import { promises as fs } from "node:fs";
import { basename, dirname, extname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { dump, load } from "js-yaml";

type ThemeTypographyRole = {
    family: string;
    fallback?: string;
    tone?: string;
};

type ThemeTypographyVariantMap = Record<string, ThemeTypographyRole>;

type ThemePalette = {
    page: {
        background: string;
        tint?: string;
        deep?: string;
    };
    text: {
        default: string;
        muted: string;
        soft?: string;
        heading: string;
        inverse?: string;
    };
    accents: {
        primary: string;
        primaryStrong?: string;
        secondary?: string;
        secondaryStrong?: string;
        soft?: string;
        tint?: string;
        warm?: string;
        warmSoft?: string;
        warmTint?: string;
    };
    surfaces: {
        default: string;
        muted?: string;
        strong?: string;
        deep?: string;
        border: string;
        borderStrong?: string;
        hero?: string;
        cta?: string;
        panel?: string;
        shadow?: string;
        shadowStrong?: string;
    };
};

type NamedSurfaceConfig = {
    name: string;
    purpose?: string;
    background?: string;
    color?: string;
    border?: string;
    shadow?: string;
};

export type ThemeGeneratorConfig = {
    id: string;
    name: string;
    selector?: string;
    version?: number;
    summary?: string;
    philosophy?: Record<string, unknown>;
    recommended_use_cases?: string[];
    authoring_rules?: string[];
    example?: Record<string, unknown>;
    typography: {
        body: ThemeTypographyRole;
        heading: ThemeTypographyRole;
        variants?: ThemeTypographyVariantMap;
    };
    palette: ThemePalette;
    named_surfaces?: NamedSurfaceConfig[];
};

export type ThemeEntry = {
    id: string;
    src: string;
};

export type GenerateExternalThemeOptions = {
    configPath: string;
    cssOutPath: string;
    yamlOutPath?: string;
    mdOutPath?: string;
};

const TOOLS_ROOT = dirname(fileURLToPath(import.meta.url));
const SRC_ROOT = resolve(TOOLS_ROOT, "../..");
const THEMES_ROOT = resolve(SRC_ROOT, "themes");
const GENERATED_ROOT = resolve(SRC_ROOT, ".generated/themes");

function toPosix(pathValue: string): string {
    return pathValue.replace(/\\/g, "/");
}

function quoteFont(role: ThemeTypographyRole): string {
    return role.fallback ? `${role.family}, ${role.fallback}` : role.family;
}

function toCssVarSegment(value: string): string {
    return value
        .trim()
        .replace(/[^a-zA-Z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "")
        .toLowerCase();
}

function buildTypographyVariantVariables(config: ThemeGeneratorConfig): string {
    return Object.entries(config.typography.variants ?? {})
        .map(([name, role]) => `    --jx-font-${toCssVarSegment(name)}: ${quoteFont(role)};`)
        .join("\n");
}

function stringifyConfig(config: ThemeGeneratorConfig): string {
    return dump({
        ...config,
        selector: config.selector ?? `theme="${config.id}"`,
        version: config.version ?? 1,
    }, { lineWidth: 120 });
}

function formatObjectList(value: unknown, indent = ""): string[] {
    if (!value || typeof value !== "object") {
        return [];
    }

    return Object.entries(value as Record<string, unknown>).flatMap(([key, nested]) => {
        if (Array.isArray(nested)) {
            return [
                `${indent}- \`${key}\`:`,
                ...nested.map((item) => `${indent}  - ${String(item)}`),
            ];
        }

        if (nested && typeof nested === "object") {
            return [
                `${indent}- \`${key}\`:`,
                ...formatObjectList(nested, `${indent}  `),
            ];
        }

        return [`${indent}- \`${key}\`: ${String(nested)}`];
    });
}

function buildThemeReferenceMarkdown(config: ThemeGeneratorConfig, sourceLabel: string): string {
    const selector = config.selector ?? `theme="${config.id}"`;
    const typographyVariants = Object.entries(config.typography.variants ?? {});
    const namedSurfaces = config.named_surfaces ?? [];
    const philosophy = formatObjectList(config.philosophy);
    const example = formatObjectList(config.example);

    return [
        `# ${config.name} Theme Reference`,
        "",
        `Generated by Juice theme generator from \`${sourceLabel}\`.`,
        "",
        "## Core",
        "",
        `- Theme id: \`${config.id}\``,
        `- Root selector: \`${selector}\``,
        `- Version: \`${config.version ?? 1}\``,
        ...(config.summary ? [`- Summary: ${config.summary}`] : []),
        "",
        "## Brand-Specific Attribute Values",
        "",
        `- Theme root: \`[theme="${config.id}"]\``,
        ...(namedSurfaces.length
            ? namedSurfaces.flatMap((surface) => [
                `- Named surface: \`[surface="${surface.name}"]\`${surface.purpose ? ` - ${surface.purpose}` : ""}`,
            ])
            : ["- No named surfaces declared in this theme config."]),
        "",
        "## Typography",
        "",
        `- Body: \`${quoteFont(config.typography.body)}\`${config.typography.body.tone ? ` - ${config.typography.body.tone}` : ""}`,
        `- Heading: \`${quoteFont(config.typography.heading)}\`${config.typography.heading.tone ? ` - ${config.typography.heading.tone}` : ""}`,
        ...(typographyVariants.length
            ? [
                "",
                "### Typography Variants",
                "",
                ...typographyVariants.map(([name, role]) =>
                    `- \`${name}\`: \`${quoteFont(role)}\`${role.tone ? ` - ${role.tone}` : ""}`),
            ]
            : []),
        "",
        "## Palette",
        "",
        "### Page",
        "",
        ...Object.entries(config.palette.page).map(([key, value]) => `- \`${key}\`: \`${value}\``),
        "",
        "### Text",
        "",
        ...Object.entries(config.palette.text).map(([key, value]) => `- \`${key}\`: \`${value}\``),
        "",
        "### Accents",
        "",
        ...Object.entries(config.palette.accents).map(([key, value]) => `- \`${key}\`: \`${value}\``),
        "",
        "### Surfaces",
        "",
        ...Object.entries(config.palette.surfaces).map(([key, value]) => `- \`${key}\`: \`${value}\``),
        "",
        "## Generated CSS Variables",
        "",
        `- \`--jx-body-font\`: \`${quoteFont(config.typography.body)}\``,
        `- \`--jx-heading-font\`: \`${quoteFont(config.typography.heading)}\``,
        ...typographyVariants.map(([name, role]) => `- \`--jx-font-${toCssVarSegment(name)}\`: \`${quoteFont(role)}\``),
        `- \`--jx-accent\`: \`${config.palette.accents.primary}\``,
        `- \`--jx-accent-secondary\`: \`${config.palette.accents.secondary ?? config.palette.accents.primary}\``,
        `- \`--jx-surface\`: \`${config.palette.surfaces.default}\``,
        `- \`--jx-panel-background\`: \`${config.palette.surfaces.panel ?? config.palette.surfaces.muted ?? config.palette.surfaces.default}\``,
        "",
        ...(config.recommended_use_cases?.length
            ? [
                "## Recommended Use Cases",
                "",
                ...config.recommended_use_cases.map((item) => `- ${item}`),
                "",
            ]
            : []),
        ...(config.authoring_rules?.length
            ? [
                "## Authoring Rules",
                "",
                ...config.authoring_rules.map((item) => `- ${item}`),
                "",
            ]
            : []),
        ...(philosophy.length
            ? [
                "## Philosophy",
                "",
                ...philosophy,
                "",
            ]
            : []),
        ...(example.length
            ? [
                "## Example",
                "",
                ...example,
                "",
            ]
            : []),
        "## Notes",
        "",
        "- This reference is generated from the theme config only.",
        "- App-local attributes such as product-card hooks or brand-specific component selectors are not inferred here unless they exist in the theme config itself.",
        "",
    ].join("\n");
}

function buildNamedSurfaceRules(config: ThemeGeneratorConfig): string {
    return (config.named_surfaces ?? []).map((surface) => {
        const background = surface.background ?? "var(--jx-surface-muted)";
        const color = surface.color ?? "var(--jx-heading)";
        const border = surface.border ?? "var(--jx-border)";
        const shadow = surface.shadow ?? "var(--jx-shadow)";

        return `
[theme="${config.id}"][surface="${surface.name}"],
[theme="${config.id}"] [surface="${surface.name}"] {
    background: ${background};
    color: ${color};
    border: 1px solid ${border};
    box-shadow: ${shadow};
}

[theme="${config.id}"][surface="${surface.name}"] :where(h1, h2, h3, h4, h5, h6, strong, b),
[theme="${config.id}"] [surface="${surface.name}"] :where(h1, h2, h3, h4, h5, h6, strong, b) {
    color: ${color};
}
`.trim();
    }).join("\n\n");
}

export function buildThemeStylesheet(config: ThemeGeneratorConfig, sourceLabel: string): string {
    const pageTint = config.palette.page.tint ?? config.palette.page.background;
    const pageDeep = config.palette.page.deep ?? config.palette.surfaces.deep ?? config.palette.text.heading;
    const textSoft = config.palette.text.soft ?? config.palette.text.muted;
    const textInverse = config.palette.text.inverse ?? "rgba(255, 255, 255, 0.82)";
    const surfaceMuted = config.palette.surfaces.muted ?? config.palette.surfaces.default;
    const surfaceStrong = config.palette.surfaces.strong ?? config.palette.surfaces.default;
    const surfaceDeep = config.palette.surfaces.deep ?? pageDeep;
    const borderStrong = config.palette.surfaces.borderStrong ?? config.palette.surfaces.border;
    const heroBackground = config.palette.surfaces.hero ?? config.palette.page.background;
    const ctaBackground = config.palette.surfaces.cta ?? config.palette.accents.primary;
    const panelBackground = config.palette.surfaces.panel ?? surfaceMuted;
    const shadow = config.palette.surfaces.shadow ?? "0 18px 48px rgba(0, 0, 0, 0.08)";
    const shadowStrong = config.palette.surfaces.shadowStrong ?? shadow;
    const accentPrimaryStrong = config.palette.accents.primaryStrong ?? config.palette.accents.primary;
    const accentSecondary = config.palette.accents.secondary ?? config.palette.accents.primary;
    const accentSecondaryStrong = config.palette.accents.secondaryStrong ?? accentSecondary;
    const accentSoft = config.palette.accents.soft ?? config.palette.accents.primary;
    const accentTint = config.palette.accents.tint ?? accentSoft;
    const warm = config.palette.accents.warm ?? accentSecondary;
    const warmSoft = config.palette.accents.warmSoft ?? accentTint;
    const warmTint = config.palette.accents.warmTint ?? warmSoft;
    const namedSurfaces = buildNamedSurfaceRules(config);
    const typographyVariantVariables = buildTypographyVariantVariables(config);
    const accordionTriggerOpen = config.palette.accents.soft
        ? "var(--jx-accent-soft)"
        : "var(--jx-surface-muted)";

    return `/*
  Generated by Juice theme generator.
  Source config: ${sourceLabel}
*/

[theme="${config.id}"] {
    --jx-page: ${config.palette.page.background};
    --jx-page-tint: ${pageTint};
    --jx-page-deep: ${pageDeep};
    --jx-surface: ${config.palette.surfaces.default};
    --jx-surface-muted: ${surfaceMuted};
    --jx-surface-strong: ${surfaceStrong};
    --jx-surface-deep: ${surfaceDeep};
    --jx-border: ${config.palette.surfaces.border};
    --jx-border-strong: ${borderStrong};
    --jx-shadow: ${shadow};
    --jx-shadow-strong: ${shadowStrong};

    --jx-text: ${config.palette.text.default};
    --jx-text-muted: ${config.palette.text.muted};
    --jx-text-soft: ${textSoft};
    --jx-text-inverse: ${textInverse};
    --jx-heading: ${config.palette.text.heading};

    --jx-body-font: ${quoteFont(config.typography.body)};
    --jx-heading-font: ${quoteFont(config.typography.heading)};
${typographyVariantVariables ? `${typographyVariantVariables}\n` : ""}

    --jx-accent: ${config.palette.accents.primary};
    --jx-accent-strong: ${accentPrimaryStrong};
    --jx-accent-secondary: ${accentSecondary};
    --jx-accent-secondary-strong: ${accentSecondaryStrong};
    --jx-accent-soft: ${accentSoft};
    --jx-accent-tint: ${accentTint};
    --jx-warm: ${warm};
    --jx-warm-soft: ${warmSoft};
    --jx-warm-tint: ${warmTint};

    --jx-hero-background: ${heroBackground};
    --jx-cta-background: ${ctaBackground};
    --jx-panel-background: ${panelBackground};

    /* Accordion chrome roles — same names as library themes; existing --jx-* only. */
    --jx-trigger: var(--jx-surface-strong);
    --jx-trigger-hover: var(--jx-surface-muted);
    --jx-trigger-open: ${accordionTriggerOpen};
    --jx-chevron: var(--jx-accent);
    --jx-panel-rule: var(--jx-border);
    --jx-focus-ring: var(--jx-accent);
    --juice-accordion-trigger: var(--jx-trigger);
    --juice-accordion-trigger-hover: var(--jx-trigger-hover);
    --juice-accordion-trigger-open: var(--jx-trigger-open);
    --juice-accordion-chevron: var(--jx-chevron);
    --juice-accordion-panel-rule: var(--jx-panel-rule);
    --juice-accordion-focus-ring: var(--jx-focus-ring);

    /* Tabs chrome roles — surface/text controls, not the CTA fill. */
    --jx-tabs-trigger: transparent;
    --jx-tabs-trigger-hover: transparent;
    --jx-tabs-trigger-active: transparent;
    --jx-tabs-text: var(--jx-text-soft);
    --jx-tabs-text-hover: var(--jx-heading);
    --jx-tabs-text-active: var(--jx-accent);
    --jx-tabs-indicator: var(--jx-accent);
    --jx-tabs-list-rule: var(--jx-border);
    --jx-tabs-focus-ring: var(--jx-accent);
    --juice-tabs-trigger: var(--jx-tabs-trigger);
    --juice-tabs-trigger-hover: var(--jx-tabs-trigger-hover);
    --juice-tabs-trigger-active: var(--jx-tabs-trigger-active);
    --juice-tabs-text: var(--jx-tabs-text);
    --juice-tabs-text-hover: var(--jx-tabs-text-hover);
    --juice-tabs-text-active: var(--jx-tabs-text-active);
    --juice-tabs-indicator: var(--jx-tabs-indicator);
    --juice-tabs-list-rule: var(--jx-tabs-list-rule);
    --juice-tabs-focus-ring: var(--jx-tabs-focus-ring);

    /* Surface tone roles — frosted / elevated / recessed from existing --jx-* tokens. */
    --juice-surface-soft-bg: var(--jx-surface);
    --juice-surface-soft-border: var(--jx-border);
    --juice-surface-soft-shadow: var(--jx-shadow);
    --juice-surface-soft-blur: 10px;
    --juice-surface-strong-bg: var(--jx-surface-strong);
    --juice-surface-strong-border: var(--jx-border-strong);
    --juice-surface-strong-shadow: var(--jx-shadow-strong);
    --juice-surface-strong-blur: 0px;
    --juice-surface-muted-bg: var(--jx-surface-muted);
    --juice-surface-muted-border: var(--jx-border);
    --juice-surface-muted-shadow: none;
    --juice-surface-muted-blur: 0px;

    /* Border strength — existing --jx-border tokens; 1px hairline vs 2px rule. */
    --juice-border-strength-soft-width: 1px;
    --juice-border-strength-soft-color: var(--jx-border);
    --juice-border-strength-bold-width: 2px;
    --juice-border-strength-bold-color: var(--jx-border-strong);

    /* Shadow tone — existing --jx-page-deep / --jx-warm / --jx-shadow. */
    --juice-shadow-tone-cool-color: color-mix(in srgb, var(--jx-page-deep) 20%, transparent);
    --juice-shadow-tone-cool-shadow: var(--jx-shadow);
    --juice-shadow-tone-warm-color: color-mix(in srgb, var(--jx-warm) 22%, transparent);
    --juice-shadow-tone-warm-shadow: 0 18px 40px -28px color-mix(in srgb, var(--jx-warm) 22%, transparent);

    /* Overlay — frost veil / accent-tint wash from existing --jx-* tokens. */
    --juice-overlay-frost-wash: color-mix(in srgb, var(--jx-surface) 42%, transparent);
    --juice-overlay-frost-layer: linear-gradient(var(--juice-overlay-frost-wash), var(--juice-overlay-frost-wash));
    --juice-overlay-tint-wash: color-mix(in srgb, var(--jx-accent-tint) 36%, transparent);
    --juice-overlay-tint-layer: linear-gradient(var(--juice-overlay-tint-wash), var(--juice-overlay-tint-wash));

    /* Modal chrome — dimming scrim + elevated panel from existing --jx-* tokens.
       Close is a surface control, not the CTA fill. */
    --jx-modal-overlay: color-mix(in srgb, var(--jx-page-deep) 70%, transparent);
    --jx-modal-panel: var(--jx-surface);
    --jx-modal-panel-border: var(--jx-border);
    --jx-modal-panel-shadow: var(--jx-shadow-strong);
    --jx-modal-close: var(--jx-surface);
    --jx-modal-close-color: var(--jx-heading);
    --jx-modal-close-hover: var(--jx-surface-muted);
    --jx-modal-focus-ring: var(--jx-accent);
    --juice-modal-overlay: var(--jx-modal-overlay);
    --juice-modal-panel: var(--jx-modal-panel);
    --juice-modal-panel-border: var(--jx-modal-panel-border);
    --juice-modal-panel-shadow: var(--jx-modal-panel-shadow);
    --juice-modal-close: var(--jx-modal-close);
    --juice-modal-close-color: var(--jx-modal-close-color);
    --juice-modal-close-hover: var(--jx-modal-close-hover);
    --juice-modal-focus-ring: var(--jx-modal-focus-ring);

    /* Drawer chrome — dimming scrim + edge panel from existing --jx-* tokens.
       Close is a surface control, not the CTA fill. */
    --jx-drawer-overlay: color-mix(in srgb, var(--jx-page-deep) 70%, transparent);
    --jx-drawer-panel: var(--jx-surface);
    --jx-drawer-panel-border: var(--jx-border);
    --jx-drawer-panel-shadow: var(--jx-shadow-strong);
    --jx-drawer-close: var(--jx-surface);
    --jx-drawer-close-color: var(--jx-heading);
    --jx-drawer-close-hover: var(--jx-surface-muted);
    --jx-drawer-focus-ring: var(--jx-accent);
    --juice-drawer-overlay: var(--jx-drawer-overlay);
    --juice-drawer-panel: var(--jx-drawer-panel);
    --juice-drawer-panel-border: var(--jx-drawer-panel-border);
    --juice-drawer-panel-shadow: var(--jx-drawer-panel-shadow);
    --juice-drawer-close: var(--jx-drawer-close);
    --juice-drawer-close-color: var(--jx-drawer-close-color);
    --juice-drawer-close-hover: var(--jx-drawer-close-hover);
    --juice-drawer-focus-ring: var(--jx-drawer-focus-ring);

    /* Toast chrome — non-modal stack + panel from existing --jx-* tokens.
       Close is a surface control, not the CTA fill. Status remaps accent /
       page-deep / secondary / warm. */
    --jx-toast-panel: var(--jx-surface);
    --jx-toast-panel-border: var(--jx-border);
    --jx-toast-panel-shadow: var(--jx-shadow-strong);
    --jx-toast-ink: var(--jx-text);
    --jx-toast-close: var(--jx-surface);
    --jx-toast-close-color: var(--jx-heading);
    --jx-toast-close-hover: var(--jx-surface-muted);
    --jx-toast-focus-ring: var(--jx-accent);
    --jx-toast-success: var(--jx-accent);
    --jx-toast-success-soft: var(--jx-accent-soft);
    --jx-toast-error: var(--jx-page-deep);
    --jx-toast-error-soft: color-mix(in srgb, var(--jx-page-deep) 12%, var(--jx-surface));
    --jx-toast-info: var(--jx-accent-secondary);
    --jx-toast-info-soft: var(--jx-accent-tint);
    --jx-toast-warning: var(--jx-warm);
    --jx-toast-warning-soft: var(--jx-warm-soft);
    --juice-toast-panel: var(--jx-toast-panel);
    --juice-toast-panel-border: var(--jx-toast-panel-border);
    --juice-toast-panel-shadow: var(--jx-toast-panel-shadow);
    --juice-toast-ink: var(--jx-toast-ink);
    --juice-toast-close: var(--jx-toast-close);
    --juice-toast-close-color: var(--jx-toast-close-color);
    --juice-toast-close-hover: var(--jx-toast-close-hover);
    --juice-toast-focus-ring: var(--jx-toast-focus-ring);
    --juice-toast-success: var(--jx-toast-success);
    --juice-toast-success-soft: var(--jx-toast-success-soft);
    --juice-toast-error: var(--jx-toast-error);
    --juice-toast-error-soft: var(--jx-toast-error-soft);
    --juice-toast-info: var(--jx-toast-info);
    --juice-toast-info-soft: var(--jx-toast-info-soft);
    --juice-toast-warning: var(--jx-toast-warning);
    --juice-toast-warning-soft: var(--jx-toast-warning-soft);

    /* Banner chrome — inline alert / callout from existing --jx-* tokens.
       Close is a surface control, not the CTA fill. Status remaps accent /
       page-deep / secondary / warm. Distinct from toast stack. */
    --jx-banner-panel: var(--jx-surface);
    --jx-banner-panel-border: var(--jx-border);
    --jx-banner-ink: var(--jx-text);
    --jx-banner-close: var(--jx-surface);
    --jx-banner-close-color: var(--jx-heading);
    --jx-banner-close-hover: var(--jx-surface-muted);
    --jx-banner-focus-ring: var(--jx-accent);
    --jx-banner-success: var(--jx-accent);
    --jx-banner-success-soft: var(--jx-accent-soft);
    --jx-banner-error: var(--jx-page-deep);
    --jx-banner-error-soft: color-mix(in srgb, var(--jx-page-deep) 12%, var(--jx-surface));
    --jx-banner-info: var(--jx-accent-secondary);
    --jx-banner-info-soft: var(--jx-accent-tint);
    --jx-banner-warning: var(--jx-warm);
    --jx-banner-warning-soft: var(--jx-warm-soft);
    --juice-banner-panel: var(--jx-banner-panel);
    --juice-banner-panel-border: var(--jx-banner-panel-border);
    --juice-banner-ink: var(--jx-banner-ink);
    --juice-banner-close: var(--jx-banner-close);
    --juice-banner-close-color: var(--jx-banner-close-color);
    --juice-banner-close-hover: var(--jx-banner-close-hover);
    --juice-banner-focus-ring: var(--jx-banner-focus-ring);
    --juice-banner-success: var(--jx-banner-success);
    --juice-banner-success-soft: var(--jx-banner-success-soft);
    --juice-banner-error: var(--jx-banner-error);
    --juice-banner-error-soft: var(--jx-banner-error-soft);
    --juice-banner-info: var(--jx-banner-info);
    --juice-banner-info-soft: var(--jx-banner-info-soft);
    --juice-banner-warning: var(--jx-banner-warning);
    --juice-banner-warning-soft: var(--jx-banner-warning-soft);

    /* Popover chrome — anchored floating panel from existing --jx-* tokens.
       Close is a surface control, not the CTA fill. */
    --jx-popover-panel: var(--jx-surface);
    --jx-popover-panel-border: var(--jx-border);
    --jx-popover-panel-shadow: var(--jx-shadow-strong);
    --jx-popover-ink: var(--jx-text);
    --jx-popover-close: var(--jx-surface);
    --jx-popover-close-color: var(--jx-heading);
    --jx-popover-close-hover: var(--jx-surface-muted);
    --jx-popover-focus-ring: var(--jx-accent);
    --juice-popover-panel: var(--jx-popover-panel);
    --juice-popover-panel-border: var(--jx-popover-panel-border);
    --juice-popover-panel-shadow: var(--jx-popover-panel-shadow);
    --juice-popover-ink: var(--jx-popover-ink);
    --juice-popover-close: var(--jx-popover-close);
    --juice-popover-close-color: var(--jx-popover-close-color);
    --juice-popover-close-hover: var(--jx-popover-close-hover);
    --juice-popover-focus-ring: var(--jx-popover-focus-ring);

    /* Wizard chrome — onboarding shell / rails / steps from existing --jx-* tokens. */
    --jx-wizard-shell: var(--jx-page);
    --jx-wizard-header: var(--jx-surface-strong);
    --jx-wizard-header-border: var(--jx-border);
    --jx-wizard-rail: var(--jx-surface-muted);
    --jx-wizard-rail-border: var(--jx-border);
    --jx-wizard-step: var(--jx-surface);
    --jx-wizard-step-border: var(--jx-border);
    --jx-wizard-step-ink: var(--jx-text-muted);
    --jx-wizard-step-current: var(--jx-accent);
    --jx-wizard-step-complete: var(--jx-accent-strong);
    --jx-wizard-step-on: var(--jx-text-inverse);
    --jx-wizard-step-connector: var(--jx-border);
    --jx-wizard-panel: var(--jx-surface);
    --jx-wizard-panel-border: var(--jx-border);
    --jx-wizard-focus-ring: var(--jx-accent);
    --juice-wizard-shell: var(--jx-wizard-shell);
    --juice-wizard-header: var(--jx-wizard-header);
    --juice-wizard-header-border: var(--jx-wizard-header-border);
    --juice-wizard-rail: var(--jx-wizard-rail);
    --juice-wizard-rail-border: var(--jx-wizard-rail-border);
    --juice-wizard-step: var(--jx-wizard-step);
    --juice-wizard-step-border: var(--jx-wizard-step-border);
    --juice-wizard-step-ink: var(--jx-wizard-step-ink);
    --juice-wizard-step-current: var(--jx-wizard-step-current);
    --juice-wizard-step-complete: var(--jx-wizard-step-complete);
    --juice-wizard-step-on: var(--jx-wizard-step-on);
    --juice-wizard-step-connector: var(--jx-wizard-step-connector);
    --juice-wizard-panel: var(--jx-wizard-panel);
    --juice-wizard-panel-border: var(--jx-wizard-panel-border);
    --juice-wizard-focus-ring: var(--jx-wizard-focus-ring);

    /* Tooltip chrome — hover/focus tip from existing --jx-* tokens.
       No close, no status. Distinct from popover. */
    --jx-tooltip-panel: var(--jx-surface);
    --jx-tooltip-panel-border: var(--jx-border);
    --jx-tooltip-panel-shadow: var(--jx-shadow-strong);
    --jx-tooltip-ink: var(--jx-text);
    --juice-tooltip-panel: var(--jx-tooltip-panel);
    --juice-tooltip-panel-border: var(--jx-tooltip-panel-border);
    --juice-tooltip-panel-shadow: var(--jx-tooltip-panel-shadow);
    --juice-tooltip-ink: var(--jx-tooltip-ink);

    /* Combobox chrome — input + listbox popup from existing --jx-* tokens.
       Trigger is a surface control, not the CTA fill. Distinct from select. */
    --jx-combobox-input: var(--jx-surface);
    --jx-combobox-input-border: var(--jx-border);
    --jx-combobox-input-ink: var(--jx-text);
    --jx-combobox-list: var(--jx-surface);
    --jx-combobox-list-border: var(--jx-border);
    --jx-combobox-list-shadow: var(--jx-shadow-strong);
    --jx-combobox-option: transparent;
    --jx-combobox-option-hover: var(--jx-surface-muted);
    --jx-combobox-option-selected: var(--jx-accent-tint);
    --jx-combobox-option-ink: var(--jx-text);
    --jx-combobox-trigger: transparent;
    --jx-combobox-trigger-ink: var(--jx-heading);
    --jx-combobox-focus-ring: var(--jx-accent);
    --juice-combobox-input: var(--jx-combobox-input);
    --juice-combobox-input-border: var(--jx-combobox-input-border);
    --juice-combobox-input-ink: var(--jx-combobox-input-ink);
    --juice-combobox-list: var(--jx-combobox-list);
    --juice-combobox-list-border: var(--jx-combobox-list-border);
    --juice-combobox-list-shadow: var(--jx-combobox-list-shadow);
    --juice-combobox-option: var(--jx-combobox-option);
    --juice-combobox-option-hover: var(--jx-combobox-option-hover);
    --juice-combobox-option-selected: var(--jx-combobox-option-selected);
    --juice-combobox-option-ink: var(--jx-combobox-option-ink);
    --juice-combobox-trigger: var(--jx-combobox-trigger);
    --juice-combobox-trigger-ink: var(--jx-combobox-trigger-ink);
    --juice-combobox-focus-ring: var(--jx-combobox-focus-ring);

    /* Menu chrome — APG menu button from existing --jx-* tokens.
       Opener is a surface control, not the CTA fill. Distinct from
       popover, combobox, and native select. */
    --jx-menu-panel: var(--jx-surface);
    --jx-menu-panel-border: var(--jx-border);
    --jx-menu-panel-shadow: var(--jx-shadow-strong);
    --jx-menu-ink: var(--jx-text);
    --jx-menu-item: transparent;
    --jx-menu-item-hover: var(--jx-surface-muted);
    --jx-menu-item-active: var(--jx-accent-tint);
    --jx-menu-separator: var(--jx-border);
    --jx-menu-focus-ring: var(--jx-accent);
    --jx-menu-opener: var(--jx-surface);
    --jx-menu-opener-ink: var(--jx-heading);
    --juice-menu-panel: var(--jx-menu-panel);
    --juice-menu-panel-border: var(--jx-menu-panel-border);
    --juice-menu-panel-shadow: var(--jx-menu-panel-shadow);
    --juice-menu-ink: var(--jx-menu-ink);
    --juice-menu-item: var(--jx-menu-item);
    --juice-menu-item-hover: var(--jx-menu-item-hover);
    --juice-menu-item-active: var(--jx-menu-item-active);
    --juice-menu-separator: var(--jx-menu-separator);
    --juice-menu-focus-ring: var(--jx-menu-focus-ring);
    --juice-menu-opener: var(--jx-menu-opener);
    --juice-menu-opener-ink: var(--jx-menu-opener-ink);

    /* Switch chrome — APG switch from existing --jx-* tokens.
       The host is a surface track, not the CTA fill. Distinct from
       checkbox and menuitemcheckbox. Idle track mixes text into
       muted so the inverse thumb still reads when surfaces.muted
       falls back to surfaces.default (same as --jx-surface). */
    --jx-switch-track: color-mix(in srgb, var(--jx-text) 18%, var(--jx-surface-muted));
    --jx-switch-track-checked: var(--jx-accent);
    --jx-switch-thumb: var(--jx-text-inverse);
    --jx-switch-thumb-checked: var(--jx-text-inverse);
    --jx-switch-focus-ring: var(--jx-accent);
    --juice-switch-track: var(--jx-switch-track);
    --juice-switch-track-checked: var(--jx-switch-track-checked);
    --juice-switch-thumb: var(--jx-switch-thumb);
    --juice-switch-thumb-checked: var(--jx-switch-thumb-checked);
    --juice-switch-focus-ring: var(--jx-switch-focus-ring);

    /* Slider chrome — APG slider from existing --jx-* tokens.
       Horizontal only. The track is a surface groove, not the CTA fill.
       Distinct from range input, progress, and scrollbar. Idle track
       mixes text into muted so the inverse thumb still reads when
       surfaces.muted falls back to surfaces.default (same as --jx-surface). */
    --jx-slider-track: color-mix(in srgb, var(--jx-text) 18%, var(--jx-surface-muted));
    --jx-slider-track-border: var(--jx-border);
    --jx-slider-fill: var(--jx-accent);
    --jx-slider-thumb: var(--jx-text-inverse);
    --jx-slider-thumb-border: var(--jx-border);
    --jx-slider-thumb-shadow: 0 1px 2px var(--jx-shadow);
    --jx-slider-focus-ring: var(--jx-accent);
    --juice-slider-track: var(--jx-slider-track);
    --juice-slider-track-border: var(--jx-slider-track-border);
    --juice-slider-fill: var(--jx-slider-fill);
    --juice-slider-thumb: var(--jx-slider-thumb);
    --juice-slider-thumb-border: var(--jx-slider-thumb-border);
    --juice-slider-thumb-shadow: var(--jx-slider-thumb-shadow);
    --juice-slider-focus-ring: var(--jx-slider-focus-ring);

    /* Checkbox chrome — APG checkbox from existing --jx-* tokens.
       The host is a surface box, not the CTA fill. Binary only.
       Distinct from switch and menuitemcheckbox. */
    --jx-checkbox-control: var(--jx-surface);
    --jx-checkbox-control-checked: var(--jx-accent);
    --jx-checkbox-border: var(--jx-border);
    --jx-checkbox-border-checked: var(--jx-accent);
    --jx-checkbox-mark: var(--jx-text-inverse);
    --jx-checkbox-focus-ring: var(--jx-accent);
    --juice-checkbox-control: var(--jx-checkbox-control);
    --juice-checkbox-control-checked: var(--jx-checkbox-control-checked);
    --juice-checkbox-border: var(--jx-checkbox-border);
    --juice-checkbox-border-checked: var(--jx-checkbox-border-checked);
    --juice-checkbox-mark: var(--jx-checkbox-mark);
    --juice-checkbox-focus-ring: var(--jx-checkbox-focus-ring);

    /* Radio chrome — APG radio from existing --jx-* tokens.
       The host is a surface disc, not the CTA fill. Group layout
       is author-owned. Distinct from switch and checkbox. */
    --jx-radio-control: var(--jx-surface);
    --jx-radio-control-checked: var(--jx-surface);
    --jx-radio-border: var(--jx-border);
    --jx-radio-border-checked: var(--jx-accent);
    --jx-radio-mark: var(--jx-accent);
    --jx-radio-focus-ring: var(--jx-accent);
    --juice-radio-control: var(--jx-radio-control);
    --juice-radio-control-checked: var(--jx-radio-control-checked);
    --juice-radio-border: var(--jx-radio-border);
    --juice-radio-border-checked: var(--jx-radio-border-checked);
    --juice-radio-mark: var(--jx-radio-mark);
    --juice-radio-focus-ring: var(--jx-radio-focus-ring);

    background:
        radial-gradient(circle at top left, var(--jx-accent-tint), transparent 25%),
        linear-gradient(180deg, var(--jx-page-tint) 0%, var(--jx-page) 100%);
    color: var(--jx-text);
    font-family: var(--jx-body-font);
}

[theme="${config.id}"] :where(main) {
    background: transparent;
    color: inherit;
}

[theme="${config.id}"] :where(section, article, aside, nav, header, footer, form) {
    background: var(--jx-surface);
    color: var(--jx-text);
}

[theme="${config.id}"] :where(nav) {
    background: var(--jx-surface-strong);
    border-bottom: 1px solid var(--jx-border);
    backdrop-filter: blur(18px);
}

[theme="${config.id}"] :where(footer) {
    background: var(--jx-surface-deep);
    color: var(--jx-text-inverse);
}

[theme="${config.id}"] :where(h1, h2, h3, h4, h5, h6) {
    color: var(--jx-heading);
    font-family: var(--jx-heading-font);
    font-weight: 700;
    line-height: 1.05;
}

[theme="${config.id}"] :where(p, span, li, label, dt, dd, blockquote) {
    color: var(--jx-text);
    font-family: var(--jx-body-font);
    line-height: 1.65;
}

[theme="${config.id}"] :where(small, figcaption, [muted]) {
    color: var(--jx-text-soft);
}

[theme="${config.id}"] :where(a) {
    color: var(--jx-text-muted);
    text-decoration: none;
    transition: color 0.2s ease;
}

[theme="${config.id}"] :where(a:hover, a:focus-visible) {
    color: var(--jx-accent);
}

[theme="${config.id}"] :where(button, input, textarea, select) {
    font-family: var(--jx-body-font);
}

[theme="${config.id}"] :where(button) {
    background: var(--jx-accent);
    color: var(--jx-text-inverse);
    border: 1px solid transparent;
    border-radius: 999px;
    box-shadow: var(--jx-shadow);
}

[theme="${config.id}"] :where(button:hover, button:focus-visible) {
    background: var(--jx-accent-strong);
}

[theme="${config.id}"] :where(input, textarea, select) {
    background: var(--jx-surface);
    color: var(--jx-text);
    border: 1px solid var(--jx-border);
    border-radius: 0.75rem;
}

[theme="${config.id}"] :where(input:focus-visible, textarea:focus-visible, select:focus-visible) {
    outline: 2px solid color-mix(in srgb, var(--jx-accent) 22%, transparent);
    border-color: var(--jx-accent);
}

[theme="${config.id}"] :where([hero]) {
    background: var(--jx-hero-background);
    color: var(--jx-text-inverse);
    border: 1px solid transparent;
    box-shadow: var(--jx-shadow-strong);
}

[theme="${config.id}"] :where([hero]) :where(h1, h2, h3, h4, h5, h6, p, span, small, a) {
    color: var(--jx-text-inverse);
}

[theme="${config.id}"] :where([card], [panel]) {
    background: var(--jx-surface);
    border: 1px solid var(--jx-border);
    box-shadow: var(--jx-shadow);
}

[theme="${config.id}"] :where([panel]) {
    background: var(--jx-panel-background);
}

[theme="${config.id}"] :where([cta]) {
    background: var(--jx-cta-background);
    color: var(--jx-text-inverse);
    border: 1px solid transparent;
    box-shadow: var(--jx-shadow-strong);
}

[theme="${config.id}"] :where([cta]) :where(h1, h2, h3, h4, h5, h6, p, span, small, a, button) {
    color: var(--jx-text-inverse);
}

[theme="${config.id}"] :where([badge]) {
    background: var(--jx-accent-tint);
    color: var(--jx-accent);
}

[theme="${config.id}"] :where([badge][warm]) {
    background: var(--jx-warm-soft);
    color: var(--jx-warm);
}

[theme="${config.id}"] :where([stat]) {
    background: var(--jx-surface);
    border: 1px solid var(--jx-border);
    box-shadow: var(--jx-shadow);
}

[theme="${config.id}"] :where([accordion]) {
    background: transparent;
    border: none;
    box-shadow: none;
}

[theme="${config.id}"] button[accordion-item] {
    background: var(--juice-accordion-trigger);
    color: var(--jx-heading);
    border: 1px solid var(--jx-border);
    border-radius: 0.75rem;
    box-shadow: none;
}

[theme="${config.id}"] button[accordion-item]::after {
    border-color: var(--juice-accordion-chevron);
}

[theme="${config.id}"] button[accordion-item]:hover,
[theme="${config.id}"] button[accordion-item]:focus-visible {
    background: var(--juice-accordion-trigger-hover);
    color: var(--jx-heading);
    box-shadow: none;
}

[theme="${config.id}"] button[accordion-item]:focus-visible {
    outline: 2px solid var(--juice-accordion-focus-ring);
    outline-offset: 2px;
}

[theme="${config.id}"] button[accordion-item][aria-expanded="true"] {
    background: var(--juice-accordion-trigger-open);
    color: var(--jx-heading);
}

[theme="${config.id}"] [accordion] [role="region"] {
    color: var(--jx-text);
    background: var(--jx-surface-muted);
    border: 1px solid var(--juice-accordion-panel-rule);
    border-radius: 0.75rem;
}

[theme="${config.id}"] :where([tabs]) {
    background: transparent;
    border: none;
    box-shadow: none;
}

[theme="${config.id}"] [tabs]:not(:has([tabs-list], [tab-panel])),
[theme="${config.id}"] [tabs-list] {
    border-bottom-color: var(--juice-tabs-list-rule);
}

[theme="${config.id}"] button[tab],
[theme="${config.id}"] [tabs] > button,
[theme="${config.id}"] [tabs-list] > button {
    background: var(--juice-tabs-trigger);
    color: var(--juice-tabs-text);
    border: none;
    border-bottom: 2px solid transparent;
    border-radius: 0;
    box-shadow: none;
}

[theme="${config.id}"] button[tab]:hover,
[theme="${config.id}"] [tabs] > button:hover,
[theme="${config.id}"] [tabs-list] > button:hover {
    background: var(--juice-tabs-trigger-hover);
    color: var(--juice-tabs-text-hover);
    box-shadow: none;
}

[theme="${config.id}"] button[tab]:focus-visible,
[theme="${config.id}"] [tabs] > button:focus-visible,
[theme="${config.id}"] [tabs-list] > button:focus-visible {
    outline: 2px solid var(--juice-tabs-focus-ring);
    outline-offset: 2px;
}

[theme="${config.id}"] button[tab][active],
[theme="${config.id}"] button[tab][aria-selected="true"],
[theme="${config.id}"] [tabs] > button[active],
[theme="${config.id}"] [tabs] > button[aria-selected="true"],
[theme="${config.id}"] [tabs-list] > button[active],
[theme="${config.id}"] [tabs-list] > button[aria-selected="true"] {
    background: var(--juice-tabs-trigger-active);
    color: var(--juice-tabs-text-active);
    border-bottom-color: var(--juice-tabs-indicator);
}

[theme="${config.id}"] [tab-panel] {
    color: var(--jx-text);
}

[theme="${config.id}"] [modal-overlay] {
    background-color: var(--juice-modal-overlay);
}

[theme="${config.id}"] [modal]:not([surfaceTone]) {
    background-color: var(--juice-modal-panel);
    border: 1px solid var(--juice-modal-panel-border);
    box-shadow: var(--juice-modal-panel-shadow);
}

[theme="${config.id}"] button[modal-close],
[theme="${config.id}"] [modal-close] {
    background: var(--juice-modal-close);
    color: var(--juice-modal-close-color);
    box-shadow: none;
}

[theme="${config.id}"] button[modal-close]:hover,
[theme="${config.id}"] [modal-close]:hover {
    background: var(--juice-modal-close-hover);
    color: var(--juice-modal-close-color);
}

[theme="${config.id}"] button[modal-close]:focus-visible,
[theme="${config.id}"] [modal-close]:focus-visible {
    outline: 2px solid var(--juice-modal-focus-ring);
    outline-offset: 2px;
}

[theme="${config.id}"] [drawer-overlay] {
    background-color: var(--juice-drawer-overlay);
}

[theme="${config.id}"] [drawer]:not([surfaceTone]) {
    background-color: var(--juice-drawer-panel);
    border: 1px solid var(--juice-drawer-panel-border);
    box-shadow: var(--juice-drawer-panel-shadow);
}

[theme="${config.id}"] button[drawer-close],
[theme="${config.id}"] [drawer-close] {
    background: var(--juice-drawer-close);
    color: var(--juice-drawer-close-color);
    box-shadow: none;
}

[theme="${config.id}"] button[drawer-close]:hover,
[theme="${config.id}"] [drawer-close]:hover {
    background: var(--juice-drawer-close-hover);
    color: var(--juice-drawer-close-color);
}

[theme="${config.id}"] button[drawer-close]:focus-visible,
[theme="${config.id}"] [drawer-close]:focus-visible {
    outline: 2px solid var(--juice-drawer-focus-ring);
    outline-offset: 2px;
}

[theme="${config.id}"] [toast]:not([surfaceTone]) {
    background-color: var(--juice-toast-panel);
    border: 1px solid var(--juice-toast-panel-border);
    box-shadow: var(--juice-toast-panel-shadow);
    color: var(--juice-toast-ink);
}

[theme="${config.id}"] [toast-title],
[theme="${config.id}"] [toast-body] {
    color: var(--juice-toast-ink);
}

[theme="${config.id}"] [toast="success"]:not([surfaceTone]) {
    background-color: var(--juice-toast-success-soft);
}

[theme="${config.id}"] [toast="success"] {
    border-left-color: var(--juice-toast-success);
}

[theme="${config.id}"] [toast="success"] [toast-title] {
    color: var(--juice-toast-success);
}

[theme="${config.id}"] [toast="error"]:not([surfaceTone]) {
    background-color: var(--juice-toast-error-soft);
}

[theme="${config.id}"] [toast="error"] {
    border-left-color: var(--juice-toast-error);
}

[theme="${config.id}"] [toast="error"] [toast-title] {
    color: var(--juice-toast-error);
}

[theme="${config.id}"] [toast="info"]:not([surfaceTone]) {
    background-color: var(--juice-toast-info-soft);
}

[theme="${config.id}"] [toast="info"] {
    border-left-color: var(--juice-toast-info);
}

[theme="${config.id}"] [toast="info"] [toast-title] {
    color: var(--juice-toast-info);
}

[theme="${config.id}"] [toast="warning"]:not([surfaceTone]) {
    background-color: var(--juice-toast-warning-soft);
}

[theme="${config.id}"] [toast="warning"] {
    border-left-color: var(--juice-toast-warning);
}

[theme="${config.id}"] [toast="warning"] [toast-title] {
    color: var(--juice-toast-warning);
}

[theme="${config.id}"] button[toast-close],
[theme="${config.id}"] [toast-close] {
    background: var(--juice-toast-close);
    color: var(--juice-toast-close-color);
    box-shadow: none;
}

[theme="${config.id}"] button[toast-close]:hover,
[theme="${config.id}"] [toast-close]:hover {
    background: var(--juice-toast-close-hover);
    color: var(--juice-toast-close-color);
}

[theme="${config.id}"] button[toast-close]:focus-visible,
[theme="${config.id}"] [toast-close]:focus-visible {
    outline: 2px solid var(--juice-toast-focus-ring);
    outline-offset: 2px;
}

[theme="${config.id}"] [banner]:not([surfaceTone]) {
    background-color: var(--juice-banner-panel);
    color: var(--juice-banner-ink);
}

[theme="${config.id}"] [banner]:not([surfaceTone]):not([banner-tone]) {
    border: 1px solid var(--juice-banner-panel-border);
}

[theme="${config.id}"] [banner-body] {
    color: var(--juice-banner-ink);
}

[theme="${config.id}"] [banner][banner-tone="success"]:not([surfaceTone]) {
    background-color: var(--juice-banner-success-soft);
}

[theme="${config.id}"] [banner][banner-tone="success"] {
    border-left: 4px solid var(--juice-banner-success);
}

[theme="${config.id}"] [banner][banner-tone="error"]:not([surfaceTone]) {
    background-color: var(--juice-banner-error-soft);
}

[theme="${config.id}"] [banner][banner-tone="error"] {
    border-left: 4px solid var(--juice-banner-error);
}

[theme="${config.id}"] [banner][banner-tone="info"]:not([surfaceTone]) {
    background-color: var(--juice-banner-info-soft);
}

[theme="${config.id}"] [banner][banner-tone="info"] {
    border-left: 4px solid var(--juice-banner-info);
}

[theme="${config.id}"] [banner][banner-tone="warning"]:not([surfaceTone]) {
    background-color: var(--juice-banner-warning-soft);
}

[theme="${config.id}"] [banner][banner-tone="warning"] {
    border-left: 4px solid var(--juice-banner-warning);
}

[theme="${config.id}"] button[banner-close],
[theme="${config.id}"] [banner-close] {
    background: var(--juice-banner-close);
    color: var(--juice-banner-close-color);
    box-shadow: none;
}

[theme="${config.id}"] button[banner-close]:hover,
[theme="${config.id}"] [banner-close]:hover {
    background: var(--juice-banner-close-hover);
    color: var(--juice-banner-close-color);
}

[theme="${config.id}"] button[banner-close]:focus-visible,
[theme="${config.id}"] [banner-close]:focus-visible {
    outline: 2px solid var(--juice-banner-focus-ring);
    outline-offset: 2px;
}

[theme="${config.id}"] [popover-panel]:not([surfaceTone]) {
    background-color: var(--juice-popover-panel);
    border: 1px solid var(--juice-popover-panel-border);
    box-shadow: var(--juice-popover-panel-shadow);
    color: var(--juice-popover-ink);
}

[theme="${config.id}"] [popover-header],
[theme="${config.id}"] [popover-body] {
    color: var(--juice-popover-ink);
}

[theme="${config.id}"] button[popover-close],
[theme="${config.id}"] [popover-close] {
    background: var(--juice-popover-close);
    color: var(--juice-popover-close-color);
    box-shadow: none;
}

[theme="${config.id}"] button[popover-close]:hover,
[theme="${config.id}"] [popover-close]:hover {
    background: var(--juice-popover-close-hover);
    color: var(--juice-popover-close-color);
}

[theme="${config.id}"] button[popover-close]:focus-visible,
[theme="${config.id}"] [popover-close]:focus-visible {
    outline: 2px solid var(--juice-popover-focus-ring);
    outline-offset: 2px;
}

[theme="${config.id}"] [tooltip-panel]:not([surfaceTone]) {
    background-color: var(--juice-tooltip-panel);
    border: 1px solid var(--juice-tooltip-panel-border);
    box-shadow: var(--juice-tooltip-panel-shadow);
    color: var(--juice-tooltip-ink);
}

[theme="${config.id}"] [combobox-input] {
    background-color: var(--juice-combobox-input);
    border: 1px solid var(--juice-combobox-input-border);
    color: var(--juice-combobox-input-ink);
}

[theme="${config.id}"] button[combobox-trigger],
[theme="${config.id}"] [combobox-trigger] {
    background: var(--juice-combobox-trigger);
    color: var(--juice-combobox-trigger-ink);
    box-shadow: none;
}

[theme="${config.id}"] [combobox-input]:focus-visible,
[theme="${config.id}"] button[combobox-trigger]:focus-visible,
[theme="${config.id}"] [combobox-trigger]:focus-visible {
    outline: 2px solid var(--juice-combobox-focus-ring);
    outline-offset: 2px;
}

[theme="${config.id}"] [combobox-list]:not([surfaceTone]) {
    background-color: var(--juice-combobox-list);
    border: 1px solid var(--juice-combobox-list-border);
    box-shadow: var(--juice-combobox-list-shadow);
}

[theme="${config.id}"] [combobox-option] {
    background-color: var(--juice-combobox-option);
    color: var(--juice-combobox-option-ink);
}

[theme="${config.id}"] [combobox-option]:hover {
    background-color: var(--juice-combobox-option-hover);
}

[theme="${config.id}"] [combobox-option][aria-selected="true"],
[theme="${config.id}"] [combobox-option="active"] {
    background-color: var(--juice-combobox-option-selected);
}

[theme="${config.id}"] [menu]:not([surfaceTone]) {
    background-color: var(--juice-menu-panel);
    border: 1px solid var(--juice-menu-panel-border);
    box-shadow: var(--juice-menu-panel-shadow);
    color: var(--juice-menu-ink);
}

[theme="${config.id}"] button[menu-button],
[theme="${config.id}"] [menu-button] {
    background: var(--juice-menu-opener);
    color: var(--juice-menu-opener-ink);
    box-shadow: none;
}

[theme="${config.id}"] [menu-button]:focus-visible,
[theme="${config.id}"] button[menu-button]:focus-visible,
[theme="${config.id}"] [menuitem]:focus-visible {
    outline: 2px solid var(--juice-menu-focus-ring);
    outline-offset: 2px;
}

[theme="${config.id}"] [menuitem] {
    background-color: var(--juice-menu-item);
    color: var(--juice-menu-ink);
}

[theme="${config.id}"] [menuitem]:hover {
    background-color: var(--juice-menu-item-hover);
}

[theme="${config.id}"] [menuitem="active"] {
    background-color: var(--juice-menu-item-active);
}

[theme="${config.id}"] [menu-separator] {
    border-top-color: var(--juice-menu-separator);
}

[theme="${config.id}"] [menu-label] {
    color: var(--juice-menu-ink);
}

[theme="${config.id}"] button[switch],
[theme="${config.id}"] [switch] {
    background: var(--juice-switch-track);
    box-shadow: none;
}

[theme="${config.id}"] button[switch][aria-checked="true"],
[theme="${config.id}"] [switch][aria-checked="true"],
[theme="${config.id}"] [switch]:checked {
    background: var(--juice-switch-track-checked);
}

[theme="${config.id}"] [switch]:focus-visible,
[theme="${config.id}"] button[switch]:focus-visible {
    outline: 2px solid var(--juice-switch-focus-ring);
    outline-offset: 2px;
}

[theme="${config.id}"] button[slider]:not([slider="vertical"]),
[theme="${config.id}"] [slider]:not([slider="vertical"]) {
    background: transparent;
    box-shadow: none;
}

[theme="${config.id}"] button[slider-thumb],
[theme="${config.id}"] [slider-thumb] {
    background: var(--juice-slider-thumb);
    border-color: var(--juice-slider-thumb-border);
    box-shadow: var(--juice-slider-thumb-shadow);
    transform: translate(-50%, -50%);
}

[theme="${config.id}"] button[slider-thumb]:hover,
[theme="${config.id}"] [slider-thumb]:hover,
[theme="${config.id}"] button[slider-thumb]:focus-visible,
[theme="${config.id}"] [slider-thumb]:focus-visible {
    background: var(--juice-slider-thumb);
    box-shadow: var(--juice-slider-thumb-shadow);
    transform: translate(-50%, -50%);
}

[theme="${config.id}"] [slider-thumb]:focus-visible,
[theme="${config.id}"] button[slider-thumb]:focus-visible {
    outline: 2px solid var(--juice-slider-focus-ring);
    outline-offset: 2px;
}

[theme="${config.id}"] button[checkbox],
[theme="${config.id}"] [checkbox] {
    background: var(--juice-checkbox-control);
    border-color: var(--juice-checkbox-border);
    box-shadow: none;
    transform: none;
}

[theme="${config.id}"] button[checkbox][aria-checked="true"],
[theme="${config.id}"] [checkbox][aria-checked="true"],
[theme="${config.id}"] [checkbox]:checked {
    background: var(--juice-checkbox-control-checked);
    border-color: var(--juice-checkbox-border-checked);
}

[theme="${config.id}"] button[checkbox]:hover,
[theme="${config.id}"] [checkbox]:hover,
[theme="${config.id}"] button[checkbox]:focus-visible,
[theme="${config.id}"] [checkbox]:focus-visible {
    background: var(--juice-checkbox-control);
    box-shadow: none;
    transform: none;
}

[theme="${config.id}"] button[checkbox][aria-checked="true"]:hover,
[theme="${config.id}"] [checkbox][aria-checked="true"]:hover,
[theme="${config.id}"] [checkbox]:checked:hover,
[theme="${config.id}"] button[checkbox][aria-checked="true"]:focus-visible,
[theme="${config.id}"] [checkbox][aria-checked="true"]:focus-visible,
[theme="${config.id}"] [checkbox]:checked:focus-visible {
    background: var(--juice-checkbox-control-checked);
    border-color: var(--juice-checkbox-border-checked);
    box-shadow: none;
    transform: none;
}

[theme="${config.id}"] [checkbox]:focus-visible,
[theme="${config.id}"] button[checkbox]:focus-visible {
    outline: 2px solid var(--juice-checkbox-focus-ring);
    outline-offset: 2px;
}

[theme="${config.id}"] button[radio],
[theme="${config.id}"] [radio] {
    background: var(--juice-radio-control);
    border-color: var(--juice-radio-border);
    box-shadow: none;
    transform: none;
}

[theme="${config.id}"] button[radio][aria-checked="true"],
[theme="${config.id}"] [radio][aria-checked="true"],
[theme="${config.id}"] [radio]:checked {
    background: var(--juice-radio-control-checked);
    border-color: var(--juice-radio-border-checked);
}

[theme="${config.id}"] button[radio]:hover,
[theme="${config.id}"] [radio]:hover,
[theme="${config.id}"] button[radio]:focus-visible,
[theme="${config.id}"] [radio]:focus-visible {
    background: var(--juice-radio-control);
    box-shadow: none;
    transform: none;
}

[theme="${config.id}"] button[radio][aria-checked="true"]:hover,
[theme="${config.id}"] [radio][aria-checked="true"]:hover,
[theme="${config.id}"] [radio]:checked:hover,
[theme="${config.id}"] button[radio][aria-checked="true"]:focus-visible,
[theme="${config.id}"] [radio][aria-checked="true"]:focus-visible,
[theme="${config.id}"] [radio]:checked:focus-visible {
    background: var(--juice-radio-control-checked);
    border-color: var(--juice-radio-border-checked);
    box-shadow: none;
    transform: none;
}

[theme="${config.id}"] [radio]:focus-visible,
[theme="${config.id}"] button[radio]:focus-visible {
    outline: 2px solid var(--juice-radio-focus-ring);
    outline-offset: 2px;
}

${namedSurfaces}
`;
}

function isDirectoryEntry(name: string): boolean {
    return !name.startsWith(".");
}

async function discoverThemeConfigPaths(): Promise<string[]> {
    const entries = await fs.readdir(THEMES_ROOT, { withFileTypes: true });
    const paths: string[] = [];

    for (const entry of entries) {
        if (!entry.isDirectory() || entry.name === "_draft" || !isDirectoryEntry(entry.name)) {
            continue;
        }

        const configPath = join(THEMES_ROOT, entry.name, `${entry.name}.config.yaml`);

        try {
            await fs.access(configPath);
            paths.push(configPath);
        } catch {
            continue;
        }
    }

    return paths;
}

function normalizeConfig(rawConfig: unknown, filePath: string): ThemeGeneratorConfig {
    if (!rawConfig || typeof rawConfig !== "object") {
        throw new Error(`Theme config at ${filePath} did not produce an object.`);
    }

    const config = rawConfig as Partial<ThemeGeneratorConfig>;

    if (!config.id || !config.name || !config.typography || !config.palette) {
        throw new Error(`Theme config at ${filePath} is missing required fields (id, name, typography, palette).`);
    }

    return {
        ...config,
        selector: config.selector ?? `theme="${config.id}"`,
        version: config.version ?? 1,
    } as ThemeGeneratorConfig;
}

async function readThemeConfig(configPath: string): Promise<ThemeGeneratorConfig> {
    const source = await fs.readFile(configPath, "utf-8");
    return normalizeConfig(load(source), configPath);
}

export async function generateThemeArtifacts(): Promise<ThemeEntry[]> {
    await fs.mkdir(GENERATED_ROOT, { recursive: true });

    const configPaths = await discoverThemeConfigPaths();
    const generatedEntries: ThemeEntry[] = [];

    for (const configPath of configPaths) {
        const config = await readThemeConfig(configPath);
        const outDir = join(GENERATED_ROOT, config.id);
        const scssPath = join(outDir, `${config.id}.scss`);
        const yamlPath = join(outDir, `${config.id}.yaml`);
        const sourceLabel = toPosix(relative(SRC_ROOT, configPath));

        await fs.mkdir(outDir, { recursive: true });
        await fs.writeFile(scssPath, buildThemeStylesheet(config, sourceLabel), "utf-8");
        await fs.writeFile(yamlPath, stringifyConfig(config), "utf-8");

        generatedEntries.push({
            id: config.id,
            src: toPosix(relative(dirname(SRC_ROOT), scssPath)),
        });
    }

    return generatedEntries;
}

export async function generateExternalThemeArtifacts(options: GenerateExternalThemeOptions): Promise<ThemeGeneratorConfig> {
    const configPath = resolve(options.configPath);
    const cssOutPath = resolve(options.cssOutPath);
    const yamlOutPath = options.yamlOutPath ? resolve(options.yamlOutPath) : undefined;
    const mdOutPath = options.mdOutPath ? resolve(options.mdOutPath) : undefined;
    const config = await readThemeConfig(configPath);
    const sourceLabel = toPosix(options.configPath);

    await fs.mkdir(dirname(cssOutPath), { recursive: true });
    await fs.writeFile(cssOutPath, buildThemeStylesheet(config, sourceLabel), "utf-8");

    if (yamlOutPath) {
        await fs.mkdir(dirname(yamlOutPath), { recursive: true });
        await fs.writeFile(yamlOutPath, stringifyConfig(config), "utf-8");
    }

    if (mdOutPath) {
        await fs.mkdir(dirname(mdOutPath), { recursive: true });
        await fs.writeFile(mdOutPath, buildThemeReferenceMarkdown(config, sourceLabel), "utf-8");
    }

    return config;
}

async function discoverScssThemeEntries(root: string): Promise<ThemeEntry[]> {
    try {
        const themes = await fs.readdir(root, { withFileTypes: true });
        const entries: ThemeEntry[] = [];

        for (const theme of themes) {
            if (!theme.isDirectory() || theme.name === "_draft" || !isDirectoryEntry(theme.name)) {
                continue;
            }

            const scssPath = join(root, theme.name, `${theme.name}.scss`);

            try {
                await fs.access(scssPath);
                entries.push({
                    id: basename(scssPath, extname(scssPath)),
                    src: toPosix(relative(dirname(SRC_ROOT), scssPath)),
                });
            } catch {
                continue;
            }
        }

        return entries;
    } catch {
        return [];
    }
}

export async function collectThemeEntries(): Promise<ThemeEntry[]> {
    const manualEntries = await discoverScssThemeEntries(THEMES_ROOT);
    const generatedEntries = await discoverScssThemeEntries(GENERATED_ROOT);
    const entries = new Map<string, ThemeEntry>();

    for (const entry of manualEntries) {
        entries.set(entry.id, entry);
    }

    for (const entry of generatedEntries) {
        if (!entries.has(entry.id)) {
            entries.set(entry.id, entry);
        }
    }

    return [...entries.values()].sort((a, b) => a.id.localeCompare(b.id));
}

export async function collectDraftThemeEntries(): Promise<ThemeEntry[]> {
    return discoverScssThemeEntries(join(THEMES_ROOT, "_draft"));
}
