model: Tag
table: tags

fields:
  id:
    type: uuid
    primary: true
    default: {fn: uuid_v4}

  name:
    type: string
    unique: true

  slug:
    type: string
    unique: true

relations:
  posts:
    type: many-to-many
    model: Post
    join_table: post_tags