FROM minio/mc:latest

WORKDIR /seed

COPY apps/kiwipress ./apps/kiwipress
COPY packages/kiwipress ./packages/kiwipress
COPY libraries/juice ./libraries/juice
COPY libraries/nectarine ./libraries/nectarine
COPY libraries/seltzer ./libraries/seltzer
COPY libraries/sig ./libraries/sig
COPY README.md ./README.md
